contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #jennahamlin-mashwrapper channel"
    url: https://nfcore.slack.com/channels/jennahamlin-mashwrapper
    about: Discussion about the nf-core/jennahamlin-mashwrapper pipeline
