contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #jennahamlin-nf-core-mashwrapper channel"
    url: https://nfcore.slack.com/channels/jennahamlin-nf-core-mashwrapper
    about: Discussion about the nf-core/jennahamlin-nf-core-mashwrapper pipeline
